apiVersion: v1
type: cli/v1
name: schema
version: 0.1.0
runtime: subprocess
sourceURL: https://github.com/arch-anes/helm-schema
config:
  usage: schema [CHART] | schema validate [CHART] < values.yaml
  shortHelp: Generate and validate values.schema.json files
  longHelp: Generate schemas from Helm template usage or validate YAML values against generated schemas.
  ignoreFlags: false
runtimeConfig:
  platformCommand:
    - os: windows
      command: '${HELM_PLUGIN_DIR}\bin\helm-schema.exe'
    - command: '${HELM_PLUGIN_DIR}/bin/helm-schema'
  platformHooks:
    install:
      - os: windows
        command: powershell
        args:
          - -NoProfile
          - -ExecutionPolicy
          - Bypass
          - -File
          - '${HELM_PLUGIN_DIR}\install.ps1'
      - command: '${HELM_PLUGIN_DIR}/install.sh'
